### ISSUE TITLE
Parameters for create_job() etc.

### ISSUE THREAD

**Issue by andycraig** [fastforwardlabs/cmlbootstrap#6]
Hi, thank you for releasing this. I've had a try at using it but am getting stuck at knowing the parameters expected by the API.

In particular, I'm interested in using `create_job(self, params)` but I'm not sure what the expected keys of `params` are. If you have an example call to `create_job` that you could copy-paste here that in itself would be great.

Apologies in advance if this is documented somewhere and I've missed it.

Thank you.

**Comment by fletchjeff** [comment]
Hi Andy,

Here is an example for you: https://github.com/fastforwardlabs/cml_churn_demo_mlops/blob/master/8_build_project.py

This repo will eventually be folded into the [CML v2 API](https://docs.cloudera.com/machine-learning/cloud/api/topics/ml-api-v2.html), it's a stop gap to do some of the automation we need for demo automation.

**Comment by andycraig** [comment]
@fletchjeff Perfect! Just what I needed. Thank you!
